### ISSUE TITLE
more experienments would be nicer

### ISSUE THREAD

**Issue by andeyeluguo** [dbolya/yolact#32] opened 2019-05-07 09:18 UTC
the paper says that box2pix relies on an extremely light-weight backbone detector. 
I think more experienments maybe nicer. maybe like this
                  kitti            cityscape     coco        
box2pix
yolact

also ,yolact-lite maybe good,just like yolo-lite using light-weight backbone(like xception).
this is the yolact v1 just like yolo v1. 
I am wondering if the encoder-decoder achitecture or the atrous convolution may help which is adopped by deeplab v3 plus.
expecting yolact v2...

**Comment by andeyeluguo** [comment] 2019-05-09 02:57
the ssd paper says that it can increase 20% using atrous, maybe if you use it ,it can be faster.

**Comment by dbolya** [comment] 2019-05-09 07:10
Thanks for the suggestions!

For the box2pix comparison, Kitti wouldn't be fair because it has 200 training images and so naturally favors more traditional CV methods (ones that don't depend as much on training). For reference, box2pix does much better than Mask R-CNN on Kitti but that's not really a useful metric because COCO exists.

Then we can't compare against box2pix for COCO because they don't release source code and they have no COCO experiments. We'd also like a Cityscapes experiment, but that's not too high on the priority list.

I do want to train some really light version, and I'll probably include MobileNetv2 (#27) in the next version.

A trous makes the network slower actually. However its performance boost isn't relevant since we use FPN anyway which is better than a trous. Keep in mind that 33 FPS is an extremely hard threshold to hit, and any addition even if it's really lightweight and only takes 5ms would drop us down significantly in FPS (by ~5 fps).

The main improvement we want to make before the next version is getting focal loss to work, but we haven't had any luck so far.

**Comment by andeyeluguo** [comment] 2019-05-10 08:01
to increase  the AP,maybe you can try OHEM. Some papers point that facal loss does not work on some network (eg. yolo v3), good luck.

**Comment by dbolya** [comment] 2019-05-10 08:04
We _are_ using OHEM :/
And yeah, a lot of people are having trouble reproducing Focal Loss's results in other models. We're using Retinanet as a base though, so that's why we still have hope that we can get it to work.

**Comment by andeyeluguo** [comment] 2019-05-10 08:14
Also, more data augumentation may help, we can see that data augumentation strategy is crucial in one-stage detector(e.g. about 10% MAP improvement in SSD with data augumentation).

**Comment by andeyeluguo** [comment] 2019-05-10 09:54
the SSD paper says that 
"we randomly place an image on a canvas of 16* of the original image size filled with mean values before we do any  random crop operation“
I think the size of canvas should be fixed, but in your code augmentations.py, the size of canvas is not fixed(ratio = random.uniform(1, 4)), does it affect the result ?

**Comment by andeyeluguo** [comment] 2019-05-10 10:03
also, the minimum jaccard overlap with the objects is 0.1, 0,3,0.5,0.7, or 0.9, but the code 
https://github.com/dbolya/yolact/blob/d50616f36002c48eda0a1e34a75eac12ef70aae0/utils/augmentations.py#L294
has no 0.5 ratio, does it matter?

**Comment by dbolya** [comment] 2019-05-10 10:08
I don't think the specifics matter much because we actually found that training _without_ the expand and photometric distort data augmentation steps actually improves performance (by like 0.3 mAP). Removing RandomSampleCrop increases mAP early on but then starts overfitting after the first lr decay. We're looking to replace the functionality of RandomSampleCrop with not using fixed size images (like other more modern approaches; e.g., Mask R-CNN, Retinanet).

**Comment by andeyeluguo** [comment] 2019-05-10 10:29
when I want to train it on coco dataset, it shows this

[  0]      10 || B: 5.869 | C: 20.192 | M: 5.669 | S: 46.554 | T: 78.285 || ETA: 309 days, 21:55:02 || timer: 34.842
[  0]      20 || B: 5.806 | C: 18.315 | M: 5.587 | S: 29.611 | T: 59.320 || ETA: 309 days, 12:09:44 || timer: 32.849

I run it on eight 1080ti GPUs ,but it seems that I have one year to wait....

**Comment by dbolya** [comment] 2019-05-10 10:33
See #3 for training on multiple GPUs (Use `--no_jit` and follow the instructions in #3 to freeze batch norm).

**Comment by andeyeluguo** [comment] 2019-05-10 10:44
now it becomes 
[  0]      10 || B: 6.162 | C: 19.051 | M: 7.023 | S: 52.022 | T: 84.257 || ETA: 9 days, 0:52:56 || timer: 0.931
[  0]      20 || B: 6.292 | C: 17.792 | M: 6.867 | S: 33.852 | T: 64.803 || ETA: 8 days, 20:07:11 || timer: 1.003
[  0]      30 || B: 6.192 | C: 16.276 | M: 6.434 | S: 23.641 | T: 52.543 || ETA: 8 days, 16:11:52 || timer: 0.973

is it normal?

**Comment by dbolya** [comment] 2019-05-10 10:45
Hmm that still looks too long. The ETA should be max like 4 days. What command are you running and what is your OS?

**Comment by andeyeluguo** [comment] 2019-05-10 10:51
the command is 
python train.py --config=yolact_base_config --no_jit
my OS is Ubuntu 16.04.6 LTS. 
I have eight 1080TI GPUS, when I  export CUDA_VISIBLE_DEVICES=0, it shows that
[  0]      10 || B: 5.552 | C: 18.440 | M: 6.068 | S: 49.668 | T: 79.728 || ETA: 6 days, 7:10:33 || timer: 0.674
[  0]      20 || B: 5.733 | C: 16.601 | M: 6.243 | S: 29.721 | T: 58.299 || ETA: 6 days, 5:41:40 || timer: 0.650

that is weid.

**Comment by dbolya** [comment] 2019-05-10 10:53
Are you running
```export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7```
before that command? Because if using 1 GPU is faster than 8 even with `--no_jit`, that's pretty weird.

**Comment by andeyeluguo** [comment] 2019-05-10 11:03
the result like this:

export CUDA_VISIBLE_DEVICES=0
[ 0] 10 || B: 5.552 | C: 18.440 | M: 6.068 | S: 49.668 | T: 79.728 || ETA: 6 days, 7:10:33 || timer: 0.674
[ 0] 20 || B: 5.733 | C: 16.601 | M: 6.243 | S: 29.721 | T: 58.299 || ETA: 6 days, 5:41:40 || timer: 0.650

export CUDA_VISIBLE_DEVICES=0,1
[  0]      10 || B: 5.533 | C: 18.665 | M: 5.882 | S: 45.207 | T: 75.288 || ETA: 5 days, 2:59:08 || timer: 0.546
[  0]      20 || B: 5.975 | C: 16.787 | M: 6.058 | S: 26.018 | T: 54.837 || ETA: 4 days, 21:55:12 || timer: 0.528
[  0]      30 || B: 5.950 | C: 14.932 | M: 6.045 | S: 18.199 | T: 45.127 || ETA: 4 days, 21:04:23 || timer: 0.562

export CUDA_VISIBLE_DEVICES=0,1,2
[  0]      10 || B: 5.660 | C: 19.139 | M: 5.853 | S: 45.034 | T: 75.685 || ETA: 5 days, 13:35:47 || timer: 0.610
[  0]      20 || B: 5.719 | C: 17.398 | M: 6.220 | S: 25.546 | T: 54.882 || ETA: 5 days, 8:04:52 || timer: 0.549
[  0]      30 || B: 5.788 | C: 15.424 | M: 6.325 | S: 17.951 | T: 45.488 || ETA: 5 days, 5:34:09 || timer: 0.537

export CUDA_VISIBLE_DEVICES=0,1,2,3
[  0]      10 || B: 5.772 | C: 18.587 | M: 5.956 | S: 51.150 | T: 81.465 || ETA: 5 days, 17:18:46 || timer: 0.553
[  0]      20 || B: 5.899 | C: 17.107 | M: 6.320 | S: 31.186 | T: 60.511 || ETA: 5 days, 8:26:42 || timer: 0.463
[  0]      30 || B: 5.755 | C: 15.769 | M: 6.097 | S: 21.800 | T: 49.422 || ETA: 5 days, 4:22:25 || timer: 0.524

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[  0]      10 || B: 5.459 | C: 18.889 | M: 5.476 | S: 48.257 | T: 78.081 || ETA: 9 days, 11:17:45 || timer: 1.026
[  0]      20 || B: 5.935 | C: 17.274 | M: 5.802 | S: 29.483 | T: 58.495 || ETA: 8 days, 23:54:24 || timer: 1.079
[  0]      30 || B: 6.034 | C: 15.815 | M: 6.268 | S: 20.626 | T: 48.743 || ETA: 8 days, 19:10:52 || timer: 0.913

**Comment by dbolya** [comment] 2019-05-10 11:05
Hmm that's weird. I haven't done a lot of testing with multiple GPUs so I don't know if that's an expected result or not. Are you sure all 8 GPUs have nothing running? maybe one of the 8 is slowing the rest down?

**Comment by andeyeluguo** [comment] 2019-05-10 11:06
I found when it runs on eight gpu, the situation is this
 0     27350      C   python                                      2677MiB |
|    1     27350      C   python                                      1831MiB |
|    2     27350      C   python                                      1921MiB |
|    3     27350      C   python                                      1835MiB |
|    4     27350      C   python                                      1831MiB |
|    5     27350      C   python                                      1827MiB |
|    6     27350      C   python                                      1825MiB |
|    7     27350      C   python                                      1915MiB |

but when it runs on two gpu, it is this
   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 43%   64C    P2   158W / 250W |   5897MiB / 11178MiB |     81%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 49%   70C    P2   125W / 250W |   5291MiB / 11178MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 21%   33C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 21%   30C    P0    59W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:84:00.0 Off |                  N/A |
| 21%   30C    P0    58W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 21%   28C    P0    58W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:88:00.0 Off |                  N/A |
| 21%   28C    P0    59W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 21%   28C    P0    53W / 250W |      0MiB / 11178MiB |      0%      Default |

**Comment by dbolya** [comment] 2019-05-10 11:10
The memory usage there looks to be as expected. Maybe you're bottlenecked by your CPU? What CPU are you running?

**Comment by andeyeluguo** [comment] 2019-05-10 11:22
My cpu is
48  Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
when I use the top command,  I found the one python thread is using 1891%, other python thread is using 40%~80%, Maybe you are right.

**Comment by dbolya** [comment] 2019-05-10 11:26
Hmm the single thread performance of that chip is not too bad so idk. Python tends to be pretty CPU-bound though.

I'll have access to an 8 GPUs machine next week so I'll be able to optimize it then. For now I guess just run it at <8 GPUs?

**Comment by dbolya** [comment] 2019-05-10 11:32
You could also try making the modifications in #8 and train with a batch size of 32 or 64 (and lower the number of iterations) to give more work to the GPUs if it's still too long.

**Comment by andeyeluguo** [comment] 2019-05-10 11:33
Yes, if just finetune without changing backbone, it will take less than two days, I will train it on two GPUs, thank you. more GPUs will help you a lot, enjoy it and good luck.

**Comment by andeyeluguo** [comment] 2019-05-13 02:39
Have you read the paper:ESPNet: Efficient Spatial Pyramid of Dilated Convolutions for Semantic Segmentation ?
it says that 
"Our model ESPNet achives an class-wise mIOU of 60.336 and category-wise mIOU of 82.178 on the CityScapes test dataset and runs at 112 fps on the NVIDIA TitanX"
I wonder if yolact can compare with it, also it use the mIOU not AP. I don't know why.

112 fps on the NVIDIA TitanX

**Comment by dbolya** [comment] 2019-05-13 02:47
"ESPNet: Efficient Spatial Pyramid of Dilated Convolutions for **_Semantic Segmentation_**"

That's for semantic segmentation, not instance segmentation. Semantic segmentation is a much easier task that's pretty solved at this point.

**Comment by andeyeluguo** [comment] 2019-05-13 09:29
I found in the retinanet paper, it says
"In contrast RPN, our object classification subnet is deeper, uses only 3*3 convs, and does not share parameters with the box regression subnet. We found these higher-leverl design decisions to be more important than specific values of hyperparameters."
I think Maybe the author has found that focal loss does not work with your shallower head.
You says that the augumentation strategy of SSD does't work, maybe it doesn't work in retinanet too, that's why the author only use horizontal image flipping as the only form of data augmentation.  
the suggestions is keep all the same with retinanet:
1.  reproduce the retinanet paper
2.  add mask branch and the protonet.
3.  finetune from the retinanet.

**Comment by dbolya** [comment] 2019-05-13 09:43
Yup, that's what we think is the best course of action at the moment too. I've tried before to reproduce retinanet with this code base, but ran into snags which I believe to be because of the data augmentation and fixed image size. So right now our plan is to

1. Remove all data augmentation (and modify the training parameters so it doesn't overfit)
2. Preserve aspect ratio during training (since we have a batch size of 8, we might have to go the YOLO route and do multi-scale training instead of simply scaling the image)
3. Attempt to reproduce RetinaNet in this code base (our backbone is so similar, it's actually just a config change)
4. If that doesn't work, switch to a code base that has RetinaNet implemented and try implementing YOLACT in there.
5. Finally, try YOLACT with focal loss.

Hopefully that all works and we can add it to our planned YOLACT v1.1 release (coming ~1 mo. from now). I will note that our bbox backbone is actually really bad compared to all the other options out there. For instance, even if we don't evaluate masks, YOLOv3 is both faster and more accurate than our bbox backbone. Mask R-CNN observes a whopping 2 mAP boost from just training with masks (similar for Retina-Mask), so the fact that we're so much worse means that we're doing something very wrong.

This is actually my first foray into object detection and instance segmentation, so I made some very archaic decisions in the making of YOLACT which I'd like to fix now.

**Comment by andeyeluguo** [comment] 2019-07-01 08:15
How does it work about convert the mask_data to mask_coefficient ?
The mask_datas  from every pi of FPN is flatten to a line, and then reshape to[-1, 4], and then select column which has the corrsponding  positive index from the loc_data. I am wondering if what I understand is right, can you  make an simple example?

**Comment by dbolya** [comment] 2019-07-01 08:32
What line of code exactly are you talking about? The mask_data should never by reshaped to [-1, 4]. If you're talking about
```proto_coef  = mask_data[idx, cur_pos, :]```
that just selects all the mask coefficients for the positive training examples. The resulting tensor size would be [num_positive, mask_dim], and mask_dim is 32.

**Comment by andeyeluguo** [comment] 2019-07-02 03:51
the mask data's shape is W*H*ka, then it is reshaped to (W*H*a, k),
The question is how the mask data change the shape (W*H*a, k) to shape (n, k) ?
We can get some bboxes and their index (the index number is >k) from all the bbox by the threshold. and then get the predicted box from nms. But how can we can the index  of k?

**Comment by dbolya** [comment] 2019-07-02 04:06
That's what `cur_pos` does. You have `conf_t` of size (b, W\*H\*a) which comes out of `match` as "-1 if the instance is neutral, 0 if the instance is negative, and `class_idx + 1` if positive". Then, to find if the instance is positive, that's simply `pos = conf_t > 0`, which gives a boolean tensor of size (b, W\*H\*a) that is 1 where that instance is positive, and 0 otherwise.

Then when that gets passed into the mask loss function, I loop over the number of batches so we get
`cur_pos = pos[batch_idx]` of shape (W\*H\*a) that's a boolean vector specifying the positive instances in that batch.

Then we arrive at that `proto_coef = mask_data[batch_idx, cur_pos, :]` which takes the masks coeffs which are of size (b, W\*H\*a, k), selects the batch idx along the batch dimension, and selects all the elements along the second dimension that have a 1 in `cur_pos` (that's what indexing by a boolean tensor does). If we let `n` be `cur_pos.sum()`, then we can say the resulting tensor is size (n, k) for the number of positives by k.

**Comment by andeyeluguo** [comment] 2019-07-02 06:20
How does the match function produce the conf_t?
to get the mask_coefficient from the mask_data,  I think it needs this steps.
1. threshold.  for every class  found the corresponding prior bbox(the bbox before nms) index whose coresponding confidience score is bigger than threshold(e.g. 0.5). from this process ,we will get the 
this series of indexes named as prior indexes from the original indexes.
2. nms. Do the nms process with the prior indexes.  This process will get the n instance bboxes. 
3. overlap. Get the index of the max overlap bbox with the corrspongding instance bbox. The index used for the selecting the coefficient from mask_data.

**Comment by dbolya** [comment] 2019-07-02 06:42
I mean you could just look at the code, but no it's a little different than that:
1. Compute the IoU overlap between each anchor box and the GT boxes.
2. Every box > 0.5 overlap is considered positive.
3. Every box < 0.4 overlap is considered negative.
4. All others are considered neutral.

There's no NMS because we want as much training data as possible (as many positives as makes sense).

**Comment by andeyeluguo** [comment] 2019-07-02 08:02
But if Every box > 0.5 IoU is considered positive, there will be more than n instances. I think the n is the  number of gt_boxes. We can't make sure that the  number of box >0.5 IoU  is equal to number of instance.
The sentence really confused me:C is a n*k matrix of mask coefficients for n instances surviving nms and score thresholding. This sentence make me think that the matrix come after nms and score thresholding. What's more the figure 2 ,assembly  after nms also make me confused. I have debugged the code, but too much variables distort my mind.

**Comment by dbolya** [comment] 2019-07-02 08:07
_Oh_ that's what you mean. That sentence only applies during evaluation, not training.

Wait I thought we were talking about training this entire time? If this is about evaluation, then yeah that is correct. The matrix multiplication follows NMS and score thresholding. So it's predict, NMS, score threshold, assemble masks.

Sorry for the confusion.

**Comment by andeyeluguo** [comment] 2019-07-02 09:25
Do you think it will be more accurate to select the mask_coefficient from mask_data by using nms when we train? Actually, I know that it has no nms when training in retinanet or ssd. The backward will be weid using nms when training.

**Comment by dbolya** [comment] 2019-07-02 09:26
I think it would just lead to less accuracy because there would be less training data for the network to work with.

**Comment by andeyeluguo** [comment] 2019-07-04 02:41
I am trying to make yolact more faster（igmore the MAP temporarily） to remove the FPN structure of resnet 50-fpn by set the config file fpn :None. It is deemed to be more faster theoretically, but only 25.6 fps is getted, smaller than the 42.5 fps you provided. that is weird. I just change the resnet-50 config's fpn is none, and add two convolutions to adapt the change of channel.

**Comment by dbolya** [comment] 2019-07-04 04:46
Believe it or not, FPN actually makes the model much faster (it boosts Mask R-CNN by like 20ms too). The reason is resnet101 has up to 2048 features on its biggest layer, which if going straight into the prediction head, means you have a layer that's 2048 x 2048 features (and one that is 1024 x 1024, and one that's 512 x 512, etc.). When you use FPN, all of those layers get converted to a feature size of 256 and then have a 256 x 256 layer on top, and 2048 x 256 followed by a 256 x 256 layer is much faster than a 2048 x 2048 layer for instance.

I simplified the explanation a little, but that's the gist of it. FPN is much faster than no FPN.

**Comment by andeyeluguo** [comment] 2019-07-05 08:19
I saw the branch of fanyix, it has VOCDetection function. But when I try to run it, error occured. Is it support VOC for instance segmentation?

**Comment by dbolya** [comment] 2019-07-05 08:42
Pascal is not supported. Fanyi just has an old version of the code that I deleted. Don't try to checkout those branches (Fanyi's and Chong's), as there is no guarantee that the code will even run (and it probably won't, since that's just a quick testing ground for them).

We are planning to support Pascal SBD for v1.1 though.

**Comment by andeyeluguo** [comment] 2019-07-05 09:08
Maybe I shoud write some code to convert the cityscape format to coco stype.

**Comment by dbolya** [comment] 2019-07-05 09:10
I think that already exists for detectron. Maybe you could use the code here:
https://github.com/facebookresearch/Detectron/blob/master/tools/convert_cityscapes_to_coco.py

**Comment by andeyeluguo** [comment] 2019-07-05 09:11
Is there some script that can convert this? Some peaple says the detectron, but it seems does not work.

**Comment by dbolya** [comment] 2019-07-05 09:12
Do you know why it doesn't work? Are you sure you're passing in the arguments correctly?

**Comment by andeyeluguo** [comment] 2019-07-05 09:20
I just see the 
https://github.com/dbolya/yolact/issues/72 
says.
 I will try to use this script firstly, if it doe not work then I will write the code by myself.

**Comment by dbolya** [comment] 2019-09-19 15:30
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Closed by dbolya** 2019-09-19 15:30 UTC

**Comment by Maxinho96** [comment] 2020-04-07 09:03
> I just see the
> #72
> says.
> I will try to use this script firstly, if it doe not work then I will write the code by myself.

Hey @andeyeluguo what did you do in the end? Did you use the detectron script or wrote your code? Sorry if I reply after a long time :)
