### ISSUE TITLE
use original coco dataset error

### ISSUE THREAD

**Issue by jhtao1860** [dbolya/yolact#95] opened 2019-07-13 05:49 UTC
targets, masks, num_crowds = wrapper.get_args(wrapper_mask)
  File "train.py", line 119, in get_args
    x = arg[idx]
IndexError: list index out of range

**Comment by dbolya** [comment] 2019-07-13 05:55
I'm going to need more info here.

Is this an error with the current master branch or did you make any modifications? What's your pytorch version and what command did you run it with?

**Comment by jhtao1860** [comment] 2019-07-15 06:15
@dbolya   I did NOT  make any modifications， USE 4 GPUs，it crashed，but when I  use only 1 GPU， it  had no error

**Comment by dbolya** [comment] 2019-07-15 07:04
Hmm I see. What's your pytorch version? And what command did you use to run it?

I have to do some hacky things to get around Dataparallel's split function (though I found a better way, maybe I should change it), but it will only work in certain versions of pytorch because of said hackiness. Also this could be caused by having a weird batch size / num gpus ratio so the command you used would be helpful.

**Comment by dbolya** [comment] 2019-09-19 15:38
Since this has been open so long, I'm going to close it. Feel free to reopen if you have any updates.

**Closed by dbolya** 2019-09-19 15:38 UTC
