### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by QIQIVTrackingY** [dbolya/yolact#85] opened 2019-07-01 03:11 UTC
I got ' RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:131: NVRTC_ERROR unknown'.
My pytorch version is 1.0.1, cuda=9.0 ,python version is 3.5.

**Comment by dbolya** [comment] 2019-07-01 03:17
What version of Pytorch are you using (and what GPU)? That seems like a pretty obscure, potentially hardware-specific error according to [this thread](https://github.com/pytorch/pytorch/issues/16592).

Since it's a portion of JIT that throws the error, can you try disabling JIT by changing this line:
https://github.com/dbolya/yolact/blob/f46dc4385a41ed1f2df6716ecf6084081afcbec6/yolact.py#L24
to:
```use_jit = False```

**Comment by QIQIVTrackingY** [comment] 2019-07-01 10:38
Thank you! I disabled  JIT, but the problem has not been solved，My pytorch version is 1.0.1, cuda=9.0 ,python version is 3.5.  The cuda must be 10.0 or higher?

**Comment by dbolya** [comment] 2019-07-01 10:40
What GPU are you running? If it's a 20 series card, then you need CUDA 10.

**Comment by QIQIVTrackingY** [comment] 2019-07-01 10:45
My GPU is 1080Ti

**Comment by dbolya** [comment] 2019-07-01 10:57
So reading that thread in more detail, it looks like updating pytorch may potentially fix it? Try updating your Pytorch to 1.1 (YOLACT will still work, it will just take more vram). If that doesn't work, potentially update your CUDA installation to 10 because yours may have issues.

**Comment by zhangyunming** [comment] 2019-07-05 03:21
have you solve the problem ?

pytorch1.1 /1.0.1  cuda 9.0 python3.7

**Comment by zhangyunming** [comment] 2019-07-05 12:18
i have update cuda to 10.0 with pytorch1.1.0  and also get the error :
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed

**Comment by dbolya** [comment] 2019-07-05 12:24
@zhangyunming Where did you get pytorch from? You might want to try to install it from a different place (pip if you were using anaconda, or the other way around). It seems that this kind of issue is caused by your environment not being configured properly.

**Comment by zhangyunming** [comment] 2019-07-05 12:37
anaconda python3.7   
and pip install torch    
 its 1.1.0

**Comment by dbolya** [comment] 2019-07-05 12:38
Can you try uninstalling pytorch and running the command I have above?

**Comment by QIQIVTrackingY** [comment] 2019-07-05 12:47
I will try it tomorrow.With python3.7 pytorch 1.1.0  cuda9.0?


 
---Original---

**Comment by QIQIVTrackingY** [comment] 2019-07-05 12:48
Thank  you very much!


 
---Original---

**Comment by dbolya** [comment] 2019-07-05 12:49
I think the command is for python 3.6 actually. The command for python 3.7 is:
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-linux_x86_64.whl
```

**Comment by zhangyunming** [comment] 2019-07-08 03:38
> I think the command is for python 3.6 actually. The command for python 3.7 is:
> 
> ```

finally，it can run without error!

the configs are:

pytorch1.0.1/ cuda10/python3.7
should install pytorch by ：pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-linux_x86_64.whl  or pip install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-linux_x86_64.whl

thank you！老铁

**Comment by dbolya** [comment] 2019-07-08 03:39
@zhangyunming Nice!

@QIQIVTrackingY Does that command work for you?

**Comment by QIQIVTrackingY** [comment] 2019-07-10 06:36
It runs without error. The configs are cuda9.1  pytorch 1.1.0 python3. 5

Thank  you!


 
---Original---

**Comment by dbolya** [comment] 2019-07-10 09:10
Nice! I'll close the issue then.

**Closed by dbolya** 2019-07-10 09:10 UTC

**Comment by FantasyJXF** [comment] 2019-09-19 08:15
Python 3.6.8, PyTorch 1.1.0
```
pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
```

still get the same problem
```
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 795, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 563, in evalimage
    preds = net(batch)
  File "/home/work/.virtualenvs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/JXF/Segmentation/yolact/yolact.py", line 634, in forward
    return self.detect(pred_outs)
  File "/home/work/JXF/Segmentation/yolact/layers/functions/detection.py", line 75, in __call__
    decoded_boxes = decode(loc_data[batch_idx], prior_data)
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed
```

**Comment by dbolya** [comment] 2019-09-19 09:46
@FantasyJXF If nothing else works, you can disable jit with the "PYTORCH_JIT" environment variable. Precede your command with `PYTORCH_JIT=0`. For example:
```
PYTORCH_JIT=0 python eval.py --trained_model=weights/yolact_base_54_800000.pth
```
However, if JIT doesn't work even from a clean install, this might be indicative of a bigger problem. So you might get an error even with JIT disabled. If you do, post it here.

**Comment by FantasyJXF** [comment] 2019-09-19 10:44
@dbolya  Appreciating your quick responce. I use Pytorch 1.0.1  and the model runs Okay.
